### ISSUE TITLE
Upload to F-Droid

### ISSUE THREAD

**Issue by xmha97** [itsdrnoob/DataMonitor#23]
Please update this app to F-Droid and then put a link below on README.md

https://f-droid.org/packages/com.drnoob.datamonitor/

**Comment by itsdrnoob** [comment]
I'm currently working on pushing the app to play store. Will surely consider F-Droid as well

**Comment by itsdrnoob** [comment]
> According to izzy's scanner it has GMS proprietary library

I didn't see that coming.

**Comment by IzzySoft** [comment]
> I didn't see that coming.

I did. Need help? Culprit most likely is Google OSS Licenses plugin, which is known to drag that in as a dependency. See [my snippet here](https://gitlab.com/-/snippets/1896503#license-dialogs) for details and potential alternatives.

**Comment by itsdrnoob** [comment]
> Culprit most likely is Google OSS Licenses plugin

I thought OSS plugin was seperate from other core GMS libs. I'll replace it with an alternative as you mentioned in the  snippet.
Appreciate your help.

**Comment by IzzySoft** [comment]
> I thought OSS plugin was seperate from other core GMS libs.

Many thought so. And its name (carrying the term "OSS") with the plugin being Apache-2.0 licensed suggests as much. But we had it so many times already. No idea why, but it drags in non-free deps (here: GMS). You can check for yourself to make sure: `gradle :app:dependencies` should give you the dependency tree.

**Comment by itsdrnoob** [comment]
> You can check for yourself to make sure

Just checked the dependency tree, OSS plugin indeed has other GMS modules bundled within.

**Comment by IzzySoft** [comment]
NonFreeDep is one of the AFs that need manual care. Thanks for the notification – checked and removed the AF. Will take effect with the next sync today around 6 pm UTC then.

**Comment by jcperil** [comment]
What is the update on this issue?

**Comment by itsdrnoob** [comment]
> What is the update on this issue?

No updates yet, ig I've to manually issue a PR in the fdroiddata repo.

**Comment by IzzySoft** [comment]
That would speed things up indeed. For starters, here comes a template for `metadata/com.drnoob.datamonitor.yml` you could start with:

```yaml
Categories:
  - Internet
  - System
License: GPL-3.0-only
AuthorName: Dr.NooB
AuthorEmail: itsdrnoob@gmail.com
WebSite: https://forum.xda-developers.com/t/app-v1-0-data-monitor-track-all-your-data-usage-at-one-place.4356129/
SourceCode: https://github.com/itsdrnoob/DataMonitor
IssueTracker: https://github.com/itsdrnoob/DataMonitor/issues
Changelog: https://github.com/itsdrnoob/DataMonitor/releases

AutoName: Data Monitor

RepoType: git
Repo: https://github.com/itsdrnoob/DataMonitor

Builds:
  - versionName: v2.0.0
    versionCode: 7
    commit: v2.0.0
    subdir: app
    sudo:
      - apt-get update || apt-get update
      - apt-get install -y openjdk-11-jdk-headless
      - update-alternatives --auto java
    gradle:
      - yes

AutoUpdateMode: Version
UpdateCheckMode: Tags
CurrentVersion: v2.0.0
CurrentVersionCode: 7
```

Depending on the pipeline results, some adjustments might be needed – but if you're lucky it works out-of-the-box.
